let arr1=[1,2,3,4,5];
// console.log(arr1);
let arr2=new Array(6,7,8,9,10);
// console.log(arr2);
// arr1.push(6);
// console.log(arr1);
// console.log(arr1.pop());
// arr1.unshift(0);
// console.log(arr1);
// let arr3=arr1.join("6");
// console.log(arr3);
// console.log(arr1.slice(1,4));
// console.log(arr1.splice(2,2));
// console.log(arr1);
// let arr3=arr1.concat(arr2);
// let arr3=new Array(...arr1,...arr2);
// console.log(arr3);
// let arr3=[1,2,[3,4,5],6,[7,8,[9,10]]];
// console.log(arr3.flat(Infinity));
console.log(Array.from("Sujal"));
